# -*- coding: utf-8 -*-
"""Greyscale Medical Image Compression with PCA Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoOGtytQBc7fvXCuupoubQuU5_d_2V3K

**Install and Import Library PCA**
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from skimage import io, color

"""**Input Image**"""

# Step 1: Upload the image from your local machine
from google.colab import files
uploaded = files.upload()

# Step 2: Load the image using skimage
from skimage import io, color
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Assume you uploaded an image called 'example_image.jpg'
image = io.imread('example_image.jpg')

# Step 3: Convert to grayscale if the image is in RGB
if len(image.shape) == 3:
    image = color.rgb2gray(image)

# Step 4: Standardize the image (reshape to 2D matrix)
image_flattened = image.flatten()
image_normalized = (image_flattened - np.mean(image_flattened)) / np.std(image_flattened)
image_matrix = image_normalized.reshape(image.shape[0], -1)

# Step 5: Apply PCA to reduce dimensionality
n_components = 50  # You can adjust the number of principal components
pca = PCA(n_components=n_components)
image_pca = pca.fit_transform(image_matrix)

# Step 6: Reconstruct the image
image_reconstructed = pca.inverse_transform(image_pca)
image_reconstructed = (image_reconstructed - np.min(image_reconstructed)) / np.ptp(image_reconstructed)

# Step 7: Plot the original and reconstructed images
plt.figure(figsize=(10, 5))

# Plot original image
plt.subplot(1, 2, 1)
plt.imshow(image, cmap='gray')
plt.title('Original Image')
plt.axis('off')

# Plot reconstructed image
plt.subplot(1, 2, 2)
plt.imshow(image_reconstructed, cmap='gray')
plt.title(f'Reconstructed Image with {n_components} Components')
plt.axis('off')

plt.show()